package com.tangjian.app2015022601;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentTransaction;
import android.support.v4.app.ListFragment;
import android.support.v4.app.LoaderManager;
import android.support.v4.content.AsyncTaskLoader;
import android.support.v4.content.Loader;
import android.support.v7.app.ActionBarActivity;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;


public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        FragmentManager fragmentManager = getSupportFragmentManager();
        FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
        fragmentTransaction.add(R.id.container,new AppListFragment());
        fragmentTransaction.commit();
    }
    public static class AppLoader extends AsyncTaskLoader<List<Student>>{
        public AppLoader(Context context) {
            super(context);
        }

        @Override
        public List<Student> loadInBackground() {
            Log.d("Loader","loadInBackground");
            try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            List<Student> list = new ArrayList<Student>();
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            list.add(new Student("aaa",001));
            return list;
        }

        @Override
        protected void onStartLoading() {
            super.onStartLoading();
            Log.d("Loader","onStartLoading");
            onContentChanged();
        }
    }
    public  class AppListFragment extends ListFragment implements LoaderManager.LoaderCallbacks<List<Student>>{

        private StudentAdapter studentAdapter;

        @Override
        public void onActivityCreated(@Nullable Bundle savedInstanceState) {
            super.onActivityCreated(savedInstanceState);
            setListShown(false);
            getSupportLoaderManager().initLoader(0, null, this);
            Log.d("Loader","onActivityCreated");
        }

        @Override
        public void onLoaderReset(Loader<List<Student>> loader) {
            studentAdapter.setData(null);
            Log.d("Loader","onLoaderReset");
        }

        @Override
        public void onLoadFinished(Loader<List<Student>> loader, List<Student> data) {
            Log.d("Loader","onLoadFinished");
            setEmptyText("No Data");
            studentAdapter = new StudentAdapter(getActivity());
            setListAdapter(studentAdapter);
            setListShown(true);
            studentAdapter.setData(data);
        }

        @Override
        public Loader<List<Student>> onCreateLoader(int id, Bundle args) {
            Log.d("Loader","onCreateLoader");
            return new AppLoader(getActivity());
        }
    }
}


